import type { ShelterRecord } from '@/types/shelter';

// Shelters across us-east-1 region states: IL, NJ, NY, VA, MD, DC
// Capacity, bed counts, needs, and inventory are simulated for demo purposes
export const MOCK_SHELTERS: ShelterRecord[] = [
  // ── Illinois ──────────────────────────────────────────────────────────────
  {
    shelterId: 'shelter-001',
    name: 'Helping Hands of Springfield',
    address: '2200 Shale St, Springfield, IL 62703',
    phone: '(217) 522-0048',
    website: 'https://www.helpinghandsofspringfield.org',
    state: 'IL',
    beds: 14, capacity: 40, status: 'OPEN',
    needsList: [
      { item: 'blankets', priority: 'CRITICAL', fulfilled: false },
      { item: 'water bottles', priority: 'HIGH', fulfilled: false },
      { item: 'canned food', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { blankets: 5, 'water bottles': 12, 'canned food': 30 },
    updatedAt: new Date().toISOString(),
  },
  {
    shelterId: 'shelter-002',
    name: 'Contact Ministries',
    address: '1100 E Adams St, Springfield, IL 62703',
    phone: '(217) 753-3939',
    website: 'https://contactministries.com',
    state: 'IL',
    beds: 0, capacity: 30, status: 'FULL',
    needsList: [
      { item: 'diapers', priority: 'CRITICAL', fulfilled: false },
      { item: 'baby formula', priority: 'HIGH', fulfilled: false },
      { item: 'hygiene kits', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { diapers: 0, 'baby formula': 2 },
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-003',
    name: 'Salvation Army — Springfield',
    address: '1501 N 19th St, Springfield, IL 62703',
    phone: '(217) 528-7573',
    website: 'https://centralusa.salvationarmy.org/springfield',
    state: 'IL',
    beds: 22, capacity: 60, status: 'OPEN',
    needsList: [
      { item: 'work boots', priority: 'HIGH', fulfilled: false },
      { item: 'toiletries', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { 'canned food': 80, clothing: 40, blankets: 30 },
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },

  // ── New Jersey ────────────────────────────────────────────────────────────
  {
    shelterId: 'shelter-101',
    name: 'Covenant House New Jersey',
    address: '330 Washington St, Newark, NJ 07102',
    phone: '(973) 621-8705',
    website: 'https://covenanthousenj.org',
    state: 'NJ',
    beds: 18, capacity: 50, status: 'OPEN',
    needsList: [
      { item: 'blankets', priority: 'CRITICAL', fulfilled: false },
      { item: 'hygiene kits', priority: 'HIGH', fulfilled: false },
      { item: 'clothing (teens)', priority: 'HIGH', fulfilled: false },
      { item: 'backpacks', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { blankets: 10, 'hygiene kits': 8, clothing: 15 },
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-102',
    name: 'Eva\'s Village Emergency Shelter',
    address: '393 Main St, Paterson, NJ 07501',
    phone: '(973) 523-6220',
    website: 'https://www.evasvillage.org',
    state: 'NJ',
    beds: 5, capacity: 75, status: 'OPEN',
    needsList: [
      { item: 'canned food', priority: 'CRITICAL', fulfilled: false },
      { item: 'water bottles', priority: 'HIGH', fulfilled: false },
      { item: 'diapers', priority: 'HIGH', fulfilled: false },
      { item: 'warm clothing', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { 'canned food': 40, blankets: 25 },
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-103',
    name: 'Rescue Mission of Trenton',
    address: '98 Carroll St, Trenton, NJ 08609',
    phone: '(609) 695-1436',
    website: 'https://www.rescuemissionoftrenton.org',
    state: 'NJ',
    beds: 0, capacity: 45, status: 'FULL',
    needsList: [
      { item: 'toiletries', priority: 'HIGH', fulfilled: false },
      { item: 'socks', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { blankets: 20, 'canned food': 60 },
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-104',
    name: 'HomeFront Family Shelter',
    address: '1880 Princeton Ave, Lawrenceville, NJ 08648',
    phone: '(609) 989-9417',
    website: 'https://www.homefrontnj.org',
    state: 'NJ',
    beds: 12, capacity: 30, status: 'OPEN',
    needsList: [
      { item: 'baby formula', priority: 'CRITICAL', fulfilled: false },
      { item: 'diapers', priority: 'HIGH', fulfilled: false },
      { item: 'children\'s books', priority: 'LOW', fulfilled: false },
    ],
    inventory: { diapers: 5, 'baby formula': 3, blankets: 18 },
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },

  // ── New York ──────────────────────────────────────────────────────────────
  {
    shelterId: 'shelter-201',
    name: 'Bowery Mission',
    address: '227 Bowery, New York, NY 10002',
    phone: '(212) 226-6214',
    website: 'https://www.bowery.org',
    state: 'NY',
    beds: 30, capacity: 120, status: 'OPEN',
    needsList: [
      { item: 'blankets', priority: 'CRITICAL', fulfilled: false },
      { item: 'winter coats', priority: 'CRITICAL', fulfilled: false },
      { item: 'canned food', priority: 'HIGH', fulfilled: false },
      { item: 'toiletries', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { blankets: 20, 'canned food': 150, toiletries: 30 },
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-202',
    name: 'Covenant House New York',
    address: '460 W 41st St, New York, NY 10036',
    phone: '(212) 613-0300',
    website: 'https://www.covenanthouse.org/homeless-shelters/new-york',
    state: 'NY',
    beds: 45, capacity: 200, status: 'OPEN',
    needsList: [
      { item: 'hygiene kits', priority: 'HIGH', fulfilled: false },
      { item: 'clothing (teens)', priority: 'HIGH', fulfilled: false },
      { item: 'school supplies', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { 'hygiene kits': 25, clothing: 60, blankets: 80 },
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-203',
    name: 'Brooklyn Women\'s Shelter',
    address: '116 Williams Ave, Brooklyn, NY 11207',
    phone: '(718) 485-9700',
    website: 'https://www.nyc.gov/site/dhs/shelter/shelter.page',
    state: 'NY',
    beds: 0, capacity: 80, status: 'FULL',
    needsList: [
      { item: 'clothing (women)', priority: 'CRITICAL', fulfilled: false },
      { item: 'toiletries', priority: 'HIGH', fulfilled: false },
      { item: 'gift cards', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { toiletries: 15, blankets: 40 },
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-204',
    name: 'Samaritan Village — Queens',
    address: '138-02 Queens Blvd, Briarwood, NY 11435',
    phone: '(718) 206-2000',
    website: 'https://www.samaritanvillage.org',
    state: 'NY',
    beds: 8, capacity: 35, status: 'OPEN',
    needsList: [
      { item: 'water bottles', priority: 'HIGH', fulfilled: false },
      { item: 'canned food', priority: 'HIGH', fulfilled: false },
      { item: 'warm clothing', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { 'canned food': 55, blankets: 22 },
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-205',
    name: 'Albany County Family Shelter',
    address: '95 Central Ave, Albany, NY 12206',
    phone: '(518) 447-7905',
    website: 'https://www.albanycounty.com/departments/social-services',
    state: 'NY',
    beds: 20, capacity: 55, status: 'OPEN',
    needsList: [
      { item: 'diapers', priority: 'CRITICAL', fulfilled: false },
      { item: 'baby formula', priority: 'HIGH', fulfilled: false },
      { item: 'blankets', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { diapers: 10, blankets: 30, 'canned food': 70 },
    updatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },

  // ── Virginia ──────────────────────────────────────────────────────────────
  {
    shelterId: 'shelter-301',
    name: 'Doorways for Women and Families',
    address: '2020 N 14th St, Arlington, VA 22201',
    phone: '(703) 237-0925',
    website: 'https://www.doorwaysva.org',
    state: 'VA',
    beds: 10, capacity: 40, status: 'OPEN',
    needsList: [
      { item: 'clothing (women)', priority: 'CRITICAL', fulfilled: false },
      { item: 'hygiene kits', priority: 'HIGH', fulfilled: false },
      { item: 'diapers', priority: 'HIGH', fulfilled: false },
    ],
    inventory: { 'hygiene kits': 12, blankets: 20, diapers: 8 },
    updatedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-302',
    name: 'Richmond Rescue Mission',
    address: '2 W Grace St, Richmond, VA 23220',
    phone: '(804) 648-2748',
    website: 'https://www.homeagainrichmond.org',
    state: 'VA',
    beds: 35, capacity: 90, status: 'OPEN',
    needsList: [
      { item: 'blankets', priority: 'HIGH', fulfilled: false },
      { item: 'canned food', priority: 'HIGH', fulfilled: false },
      { item: 'work boots', priority: 'MEDIUM', fulfilled: false },
      { item: 'socks', priority: 'LOW', fulfilled: false },
    ],
    inventory: { blankets: 30, 'canned food': 100, clothing: 50 },
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-303',
    name: 'ACTS — A Community Shelter',
    address: '14416 Jefferson Davis Hwy, Woodbridge, VA 22191',
    phone: '(703) 221-8460',
    website: 'https://www.actspwc.org',
    state: 'VA',
    beds: 0, capacity: 60, status: 'FULL',
    needsList: [
      { item: 'toiletries', priority: 'HIGH', fulfilled: false },
      { item: 'cleaning supplies', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { blankets: 15, 'canned food': 45 },
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },

  // ── Maryland ──────────────────────────────────────────────────────────────
  {
    shelterId: 'shelter-401',
    name: 'Helping Up Mission',
    address: '1029 E Baltimore St, Baltimore, MD 21202',
    phone: '(410) 675-7500',
    website: 'https://www.helpingupmission.org',
    state: 'MD',
    beds: 40, capacity: 150, status: 'OPEN',
    needsList: [
      { item: 'winter coats', priority: 'CRITICAL', fulfilled: false },
      { item: 'blankets', priority: 'HIGH', fulfilled: false },
      { item: 'canned food', priority: 'HIGH', fulfilled: false },
      { item: 'toiletries', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { blankets: 35, 'canned food': 200, toiletries: 40 },
    updatedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-402',
    name: 'Montgomery County Family Shelter',
    address: '8900 Georgia Ave, Silver Spring, MD 20910',
    phone: '(240) 777-4000',
    website: 'https://www.montgomerycountymd.gov/HHS-Program/Program.aspx?id=SNHS/SNHSShelterSvcs-p744.html',
    state: 'MD',
    beds: 15, capacity: 50, status: 'OPEN',
    needsList: [
      { item: 'diapers', priority: 'CRITICAL', fulfilled: false },
      { item: 'baby formula', priority: 'HIGH', fulfilled: false },
      { item: 'children\'s clothing', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { diapers: 6, 'baby formula': 4, blankets: 25 },
    updatedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-403',
    name: 'Arundel House of Hope',
    address: '251 Buschs Frontage Rd, Annapolis, MD 21401',
    phone: '(410) 573-0333',
    website: 'https://www.arundelhouse.org',
    state: 'MD',
    beds: 0, capacity: 35, status: 'FULL',
    needsList: [
      { item: 'hygiene kits', priority: 'HIGH', fulfilled: false },
      { item: 'warm clothing', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { 'canned food': 80, blankets: 18 },
    updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },

  // ── Washington DC ─────────────────────────────────────────────────────────
  {
    shelterId: 'shelter-501',
    name: 'Central Union Mission',
    address: '65 Massachusetts Ave NW, Washington, DC 20001',
    phone: '(202) 745-7118',
    website: 'https://www.missiondc.org',
    state: 'DC',
    beds: 25, capacity: 100, status: 'OPEN',
    needsList: [
      { item: 'blankets', priority: 'CRITICAL', fulfilled: false },
      { item: 'winter coats', priority: 'CRITICAL', fulfilled: false },
      { item: 'canned food', priority: 'HIGH', fulfilled: false },
      { item: 'socks', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { blankets: 18, 'canned food': 120, toiletries: 25 },
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-502',
    name: 'Miriam\'s Kitchen',
    address: '2401 Virginia Ave NW, Washington, DC 20037',
    phone: '(202) 452-8926',
    website: 'https://www.miriamskitchen.org',
    state: 'DC',
    beds: 0, capacity: 70, status: 'FULL',
    needsList: [
      { item: 'canned food', priority: 'CRITICAL', fulfilled: false },
      { item: 'hygiene kits', priority: 'HIGH', fulfilled: false },
    ],
    inventory: { 'canned food': 30, blankets: 40 },
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-503',
    name: 'N Street Village',
    address: '1333 N St NW, Washington, DC 20005',
    phone: '(202) 939-2060',
    website: 'https://www.nstreetvillage.org',
    state: 'DC',
    beds: 18, capacity: 55, status: 'OPEN',
    needsList: [
      { item: 'clothing (women)', priority: 'HIGH', fulfilled: false },
      { item: 'toiletries', priority: 'HIGH', fulfilled: false },
      { item: 'gift cards', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { toiletries: 20, blankets: 30, clothing: 25 },
    updatedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
];
