import type { DonationRecord } from '@/types/shelter';

// Mutable in-memory store so PATCH /api/admin/donations/[donationId] can update status
export const MOCK_DONATIONS: DonationRecord[] = [
  {
    userId: 'user-alice',
    donationId: 'donation-001',
    shelterId: 'shelter-001',
    shelterName: 'Helping Hands of Springfield',
    donorName: 'Alice Johnson',
    donorEmail: 'alice@example.com',
    items: [
      { item: 'blankets', quantity: 10 },
      { item: 'water bottles', quantity: 24 },
    ],
    status: 'PLEDGED',
    pledgedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: 'user-bob',
    donationId: 'donation-002',
    shelterId: 'shelter-002',
    shelterName: 'Contact Ministries',
    donorName: 'Bob Martinez',
    donorEmail: 'bob@example.com',
    items: [
      { item: 'diapers', quantity: 50 },
      { item: 'baby formula', quantity: 6 },
    ],
    status: 'IN_TRANSIT',
    pledgedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: 'user-carol',
    donationId: 'donation-003',
    shelterId: 'shelter-003',
    shelterName: 'Sojourn Shelter and Services',
    donorName: 'Carol Lee',
    donorEmail: 'carol@example.com',
    items: [{ item: 'hygiene kits', quantity: 20 }],
    status: 'DELIVERED',
    pledgedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: 'user-david',
    donationId: 'donation-004',
    shelterId: 'shelter-101',
    shelterName: 'Covenant House New Jersey',
    donorName: 'David Kim',
    donorEmail: 'david@example.com',
    items: [
      { item: 'winter coats', quantity: 8 },
      { item: 'gloves', quantity: 15 },
    ],
    status: 'PLEDGED',
    pledgedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: 'user-elena',
    donationId: 'donation-005',
    shelterId: 'shelter-201',
    shelterName: 'Bowery Mission',
    donorName: 'Elena Vasquez',
    donorEmail: 'elena@example.com',
    items: [
      { item: 'blankets', quantity: 5 },
      { item: 'socks', quantity: 30 },
    ],
    status: 'DELIVERED',
    pledgedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: 'user-frank',
    donationId: 'donation-006',
    shelterId: 'shelter-501',
    shelterName: 'Central Union Mission',
    donorName: 'Frank Okafor',
    donorEmail: 'frank@example.com',
    items: [{ item: 'canned food', quantity: 48 }],
    status: 'IN_TRANSIT',
    pledgedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: 'user-grace',
    donationId: 'donation-007',
    shelterId: 'shelter-001',
    shelterName: 'Helping Hands of Springfield',
    donorName: 'Grace Nguyen',
    donorEmail: 'grace@example.com',
    items: [{ item: 'children\'s clothing', quantity: 12 }],
    status: 'PLEDGED',
    pledgedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    userId: 'user-henry',
    donationId: 'donation-008',
    shelterId: 'shelter-101',
    shelterName: 'Covenant House New Jersey',
    donorName: 'Henry Patel',
    donorEmail: 'henry@example.com',
    items: [
      { item: 'hygiene kits', quantity: 10 },
      { item: 'blankets', quantity: 3 },
    ],
    status: 'DELIVERED',
    pledgedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
