import type { ShelterRecord } from '@/types/shelter';

// Real shelters sourced from shelterlistings.org/city/springfield-il.html
// Capacity, bed counts, needs, and inventory are simulated for demo purposes
export const MOCK_SHELTERS: ShelterRecord[] = [
  {
    shelterId: 'shelter-001',
    name: 'Helping Hands of Springfield',
    address: '2200 Shale St, Springfield, IL 62703',
    phone: '(217) 522-0048',
    beds: 14,
    capacity: 40,
    status: 'OPEN',
    needsList: [
      { item: 'blankets', priority: 'CRITICAL', fulfilled: false },
      { item: 'water bottles', priority: 'HIGH', fulfilled: false },
      { item: 'canned food', priority: 'MEDIUM', fulfilled: false },
      { item: 'socks', priority: 'LOW', fulfilled: false },
    ],
    inventory: { blankets: 5, 'water bottles': 12, 'canned food': 30 },
    updatedAt: new Date().toISOString(),
  },
  {
    shelterId: 'shelter-002',
    name: 'Contact Ministries',
    address: '1100 E Adams St, Springfield, IL 62703',
    phone: '(217) 753-3939',
    beds: 0,
    capacity: 30,
    status: 'FULL',
    needsList: [
      { item: 'diapers', priority: 'CRITICAL', fulfilled: false },
      { item: 'baby formula', priority: 'HIGH', fulfilled: false },
      { item: 'hygiene kits', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { diapers: 0, 'baby formula': 2 },
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-003',
    name: 'Sojourn Shelter and Services',
    address: '1800 Westchester Blvd, Springfield, IL 62704',
    phone: '(217) 726-5100',
    beds: 8,
    capacity: 25,
    status: 'OPEN',
    needsList: [
      { item: 'clothing (women)', priority: 'HIGH', fulfilled: false },
      { item: 'toiletries', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { blankets: 20, 'hygiene kits': 15, 'canned food': 50 },
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-004',
    name: 'Inner City Mission',
    address: '1301 S Martin Luther King Jr Dr, Springfield, IL 62703',
    phone: '(217) 525-3940',
    beds: 0,
    capacity: 20,
    status: 'CLOSED',
    needsList: [
      { item: 'volunteers', priority: 'HIGH', fulfilled: false },
      { item: 'cleaning supplies', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: {},
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-005',
    name: 'Salvation Army Adult Rehabilitation Center',
    address: '1501 N 19th St, Springfield, IL 62703',
    phone: '(217) 528-7573',
    beds: 22,
    capacity: 60,
    status: 'OPEN',
    needsList: [
      { item: 'work boots', priority: 'HIGH', fulfilled: false },
      { item: 'toiletries', priority: 'MEDIUM', fulfilled: false },
      { item: 'reading glasses', priority: 'LOW', fulfilled: false },
    ],
    inventory: { 'canned food': 80, clothing: 40, blankets: 30 },
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-006',
    name: 'Rutledge Youth Foundation',
    address: '2420 Pasfield St, Springfield, IL 62702',
    phone: '(217) 525-7757',
    beds: 5,
    capacity: 18,
    status: 'OPEN',
    needsList: [
      { item: 'school supplies', priority: 'CRITICAL', fulfilled: false },
      { item: 'backpacks', priority: 'HIGH', fulfilled: false },
      { item: 'snacks', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { backpacks: 3, 'school supplies': 10 },
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-007',
    name: 'Mercy Communities Springfield',
    address: '624 S 7th St, Springfield, IL 62702',
    phone: '(217) 753-1358',
    beds: 3,
    capacity: 16,
    status: 'OPEN',
    needsList: [
      { item: 'diapers', priority: 'CRITICAL', fulfilled: false },
      { item: 'strollers', priority: 'HIGH', fulfilled: false },
      { item: 'children\'s clothing', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { diapers: 8, 'baby formula': 5, blankets: 12 },
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-008',
    name: 'Family Guidance Centers — Triangle Center',
    address: '2401 E Washington St, Springfield, IL 62703',
    phone: '(217) 544-9858',
    beds: 2,
    capacity: 6,
    status: 'OPEN',
    needsList: [
      { item: 'hygiene kits', priority: 'HIGH', fulfilled: false },
      { item: 'warm clothing', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { 'hygiene kits': 4, blankets: 6 },
    updatedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-009',
    name: 'Springfield Housing Authority',
    address: '200 N 11th St, Springfield, IL 62703',
    phone: '(217) 753-5757',
    beds: 0,
    capacity: 50,
    status: 'FULL',
    needsList: [
      { item: 'furniture donations', priority: 'HIGH', fulfilled: false },
      { item: 'kitchen supplies', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: {},
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-010',
    name: 'Prairie Center Against Sexual Assault',
    address: '208 S Mauvaisterre St, Jacksonville, IL 62650',
    phone: '(217) 744-2560',
    beds: 6,
    capacity: 12,
    status: 'OPEN',
    needsList: [
      { item: 'clothing (women)', priority: 'CRITICAL', fulfilled: false },
      { item: 'toiletries', priority: 'HIGH', fulfilled: false },
      { item: 'gift cards', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { toiletries: 10, blankets: 8 },
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-011',
    name: 'Central Illinois Foodbank Emergency Shelter',
    address: '2301 W Iles Ave, Springfield, IL 62704',
    phone: '(217) 522-4022',
    beds: 18,
    capacity: 35,
    status: 'OPEN',
    needsList: [
      { item: 'canned vegetables', priority: 'CRITICAL', fulfilled: false },
      { item: 'peanut butter', priority: 'HIGH', fulfilled: false },
      { item: 'pasta', priority: 'MEDIUM', fulfilled: false },
      { item: 'cooking oil', priority: 'LOW', fulfilled: false },
    ],
    inventory: { 'canned food': 120, pasta: 45, 'peanut butter': 20 },
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    shelterId: 'shelter-012',
    name: 'Heartland YMCA Emergency Housing',
    address: '701 S 4th St, Springfield, IL 62703',
    phone: '(217) 544-9846',
    beds: 10,
    capacity: 28,
    status: 'OPEN',
    needsList: [
      { item: 'towels', priority: 'HIGH', fulfilled: false },
      { item: 'soap', priority: 'HIGH', fulfilled: false },
      { item: 'shampoo', priority: 'MEDIUM', fulfilled: false },
    ],
    inventory: { towels: 15, soap: 30, shampoo: 12 },
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
];
